" $VIMRUNTIME refers to the versioned system directory where Vim stores its
" system runtime files -- /usr/share/vim/vim<version>.
"
" Vim will load $VIMRUNTIME/defaults.vim if the user does not have a vimrc.
" This happens after /etc/vim/vimrc(.local) are loaded, so it will override
" any settings in these files.
"
" If you don't want that to happen, uncomment the below line to prevent
" defaults.vim from being loaded.
" let g:skip_defaults_vim = 1
"
" If you would rather _use_ default.vim's settings, but have the system or
" user vimrc override its settings, then uncomment the line below.
" source $VIMRUNTIME/defaults.vim

" All Debian-specific settings are defined in $VIMRUNTIME/debian.vim and
" sourced by the call to :runtime you can find below.  If you wish to change
" any of those settings, you should do it in this file or
" /etc/vim/vimrc.local, since debian.vim will be overwritten everytime an
" upgrade of the vim packages is performed. It is recommended to make changes
" after sourcing debian.vim so your settings take precedence.

runtime! debian.vim

" Uncomment the next line to make Vim more Vi-compatible
" NOTE: debian.vim sets 'nocompatible'.  Setting 'compatible' changes
" numerous options, so any other options should be set AFTER changing
" 'compatible'.
"set compatible

" Vim5 and later versions support syntax highlighting. Uncommenting the next
" line enables syntax highlighting by default.
syntax on

" If using a dark background within the editing area and syntax highlighting
" turn on this option as well
"set background=dark

" Uncomment the following to have Vim jump to the last position when
" reopening a file
"au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
"filetype plugin indent on

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
"set showcmd		" Show (partial) command in status line.
"set showmatch		" Show matching brackets.
set ignorecase		" Do case insensitive matching
set smartcase		" Do smart case matching
"set incsearch		" Incremental search
"set autowrite		" Automatically save before commands like :next and :make
"set hidden		" Hide buffers when they are abandoned
"set mouse=a		" Enable mouse usage (all modes)
set hlsearch
set number
set relativenumber
set laststatus=2
set filetype=on

" Word expansion: typing 1 expands to 2
" ab 1 2 

" Key  bindings
" inoremap: INSERT mode
" nnoremap: COMMAND mode
" vnoremap: VISUAL mode
" *map keys to <key>
inoremap hh <esc>
nnoremap j h
nnoremap k j
nnoremap l k
nnoremap ò l
vnoremap j h
vnoremap k j
vnoremap l k
vnoremap ò l

" Rules for specific filetypes
" autocmd Filetype * command arguments
" autocmd for markdown files
autocmd FileType markdown ab prof professore
autocmd FileType markdown ab cdc Consiglio di Classe
autocmd FileType markdown ab ds dirigente scolastico
" autocmd for tex files 
autocmd FileType plaintex inoremap <p <enter><enter>\begin{figure}[h]<enter>\centering<enter>\includegraphics[width=0.8\linewidth]{}<enter>\caption{}<enter>\label{}<enter>\end{figure}<enter><enter><esc>
autocmd FileType plaintex inoremap <i \textit{}<esc>1ha


" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

