" $VIMRUNTIME refers to the versioned system directory where Vim stores its
" system runtime files -- /usr/share/vim/vim<version>.
"
" Vim will load $VIMRUNTIME/defaults.vim if the user does not have a vimrc.
" This happens after /etc/vim/vimrc(.local) are loaded, so it will override
" any settings in these files.
"
" If you don't want that to happen, uncomment the below line to prevent
" defaults.vim from being loaded.
" let g:skip_defaults_vim = 1
"
" If you would rather _use_ default.vim's settings, but have the system or
" user vimrc override its settings, then uncomment the line below.
" source $VIMRUNTIME/defaults.vim

" All Debian-specific settings are defined in $VIMRUNTIME/debian.vim and
" sourced by the call to :runtime you can find below.  If you wish to change
" any of those settings, you should do it in this file or
" /etc/vim/vimrc.local, since debian.vim will be overwritten everytime an
" upgrade of the vim packages is performed. It is recommended to make changes
" after sourcing debian.vim so your settings take precedence.

runtime! debian.vim

" Uncomment the next line to make Vim more Vi-compatible
" NOTE: debian.vim sets 'nocompatible'.  Setting 'compatible' changes
" numerous options, so any other options should be set AFTER changing
" 'compatible'.
"set compatible

" Vim5 and later versions support syntax highlighting. Uncommenting the next
" line enables syntax highlighting by default.
syntax on

" If using a dark background within the editing area and syntax highlighting
" turn on this option as well
"set background=dark

" Uncomment the following to have Vim jump to the last position when
" reopening a file
"au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
"filetype plugin indent on

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
"set showcmd		" Show (partial) command in status line.
"set showmatch		" Show matching brackets.
set ignorecase		" Do case insensitive matching
set smartcase		" Do smart case matching
"set incsearch		" Incremental search
"set autowrite		" Automatically save before commands like :next and :make
"set hidden		" Hide buffers when they are abandoned
"set mouse=a		" Enable mouse usage (all modes)
set hlsearch
set number
set relativenumber
set laststatus=2
set filetype=on
set encoding=utf-8

" Word expansion: typing 1 expands to 2
" ab 1 2 

" General Key  bindings
" inoremap: INSERT mode
" nnoremap: COMMAND mode
" vnoremap: VISUAL mode
" *map keys to <key>
inoremap jj <esc>
nnoremap \\ :%s///g<left><left><left>
nnoremap \s :s///g<left><left><left>
nnoremap z <c-v>  
nnoremap Z <s-v>

" Rules for specific filetypes
" autocmd Filetype * command arguments
" autocmd for markdown files
" Abbreviations
autocmd FileType markdown ab prof professore
autocmd FileType markdown ab cdc Consiglio di Classe
autocmd FileType markdown ab ds dirigente scolastico
autocmd FileType markdown ab cdf corso di formazione
" Key mappings
autocmd FileType markdown inoremap <i **<esc>1ha
autocmd FileType markdown inoremap <b ****<esc>2ha
autocmd FileType markdown inoremap <e ******<esc>3ha
autocmd FileType markdown inoremap -- <enter>-<space>
autocmd FileType markdown inoremap __ <enter>1.<space>
autocmd FileType markdown inoremap .. <esc>wwi<space>

" autocmd for tex files
" Key mappings
autocmd FileType tex inoremap .. <esc>1la<space>
autocmd FileType tex inoremap ,, <esc>/insert<enter>cw
autocmd FileType tex inoremap ;; <esc>?insert<enter>cw
autocmd FileType tex inoremap :: <esc>/end<enter>o<enter>
autocmd FileType tex inoremap <s-tab> <c-x><c-f>
autocmd FileType tex inoremap <tab> <c-x><c-n>
autocmd FileType tex inoremap -- <esc>o\usepackage{insert}<esc>/insert<enter>cw
autocmd FileType tex inoremap [[ <esc>b1hi[insert]<esc>?insert<enter>cw
autocmd FileType tex inoremap ]] <right>[insert]<esc>?insert<enter>cw
autocmd FileType tex inoremap << <right>{insert}<esc>?insert<enter>cw
autocmd FileType tex nnoremap >> :! xelatex *.tex && mupdf *.pdf<enter>
" Style macros
autocmd FileType tex inoremap <i \textit{}<esc>1ha
autocmd FileType tex inoremap <b \textbf{}<esc>1ha
autocmd FileType tex inoremap <c \tetxsc{}<esc>1ha
autocmd FileType tex inoremap <f \footnote{}<esc>1ha
" Macros for general environments (figure, wrapfigure, ecc.ecc.)
autocmd FileType tex inoremap <p <enter><enter>\begin{figure}[h!]<enter>\centering<enter>\includegraphics[width=insert]{insert}<enter>\caption{insert}<enter>\label{insert}<enter>\end{figure}<esc>5kA
autocmd FileType tex inoremap <w <enter><enter>\begin{wrapfigure}{r}{0.25\textwidth}<enter>\centering<enter>\includegraphics[width=insert]{insert}<enter>\caption{insert}<enter>\label{insert}<enter>\end{wrapfigure}<esc>/insert<enter>cw
autocmd FileType tex inoremap <s <enter>\begin{subfigure}{insert}<enter>\centering<enter>\includegraphics[width=insert]{insert}<enter>\caption{insert}<enter>\end{subfigure}<esc>?insert<enter>cw
autocmd Filetype tex inoremap <t <enter>\begin{table}[h]<enter>\centering<enter>\begin{tabular}{m{insert}}<enter>insert<enter>\end{tabular}<enter>\end{table}<esc>/insert<enter>cw
autocmd Filetype tex inoremap <e \begin{enumerate}<enter>\item<space>insert<enter>\item<space>insert<enter>\item<space>insert<enter>\item<space>insert<enter>\end{enumerate}<esc>/insert<enter>cw
autocmd Filetype tex inoremap <z \begin{itemize}<enter>\item<space>insert<enter>\item<space>insert<enter>\item<space>insert<enter>\item<space>insert<enter>\end{itemize}<esc>/insert<enter>cw
autocmd Filetype tex inoremap <d \begin{description}<enter>\item[insert]<space>insert<enter>\item[insert]<space>insert<enter>\item[insert]<space>insert<enter>\item[insert]<space>insert<enter>\end{description}<esc>/insert<enter>cw
autocmd Filetype tex inoremap <r \begin{insert}<enter>insert<enter>\end{insert}<esc>/insert<enter>cw

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

