#!/bin/bash
touch /home/mattia/Pictures/timestamp
scrot '%Y-%m-%d_%H:%M.png' -e 'mv $f /home/mattia/Pictures/Screenshots/'
notify-send --icon=/home/mattia/Pictures/Icons/screenshot.jpg "Screenshot tool" "It looks like there's a new screenshot occupying $(find /home/mattia/Pictures/Screenshots/ -type f -cnewer /home/mattia/Pictures/timestamp -exec du -sh {} \; | cut -f1). Check it out!"
